from helper import enter
import random

def fortune_topic():
    topics = ["love", "money", "happiness"]
    love_wealth_happiness = ""
    while love_wealth_happiness not in topics:
        love_wealth_happiness = enter('''"There much to tell but we don\'t have much time. 
        Would you like to learn about love, money, or happiness?"\n
        (Please type 'love,' 'money,' or 'happiness' to select)\n''').lower()
        if love_wealth_happiness in topics:
            enter(f"{love_wealth_happiness.title()} it is.")
            enter(random_quote(love_wealth_happiness))
        else:
            enter("Please spell correctly!")
    
## Random quote generator 
def random_quote(flag):
    my_dict = {
    "love" : ['"Open your eyes wide and keep them open all day, as you might well encounter love with a capital “L," especially if you\’re single. If you’re in a couple, this influence will mean great passion or possibly some grand project. Under the aegis of the luminous signs of the Sun and the Star, your intelligence and your intuition can really shine in the professional context. Under this auspicious influence, qualities are emerging in you that will allow you to surpass yourself, to reach your goals and to lead your projects to a successful conclusion. Make good use of your charisma and your self-assurance in order to motivate your co-workers and your partners."', '"There is no doubting it, you are radiant today, and it’s love that’s doing it, dear one! With the Sun and the Pope smiling on you, you cannot help but blossom in the presence of your significant other, and you radiate happiness all around you… With such forces of attraction, there is no chance of monotony engulfing you. If you’re single, some charming stranger might make a welcome break in your daily routine. If you are in a committed relationship, you enjoy perfect harmony! At work, the combined positive energies of the Devil and the Sun are indicating some brilliant success or dazzling social advancement! Your colleagues will be queuing up to acknowledge your leadership qualities, your decisiveness and strategic intelligence. This is a very successful phase that is going to give a tremendous boost to your career. Don\'t change a thing, you\'re just perfect!"', '"Be an impartial observer in your own love life today. Instead of complaining that things aren\'t fair, try to be honest and loyal even if you don\'t get the same in return. Serve as a peacemaker. Justice says that there\'s no use in trying to keep track of all of the ways you\'ve been wronged, because everything evens out in the end."', '"The Moon guides your emotions and subconscious, and the appearance of this card shows that you are ready to trust yourself and overcome your romantic fears today. What are you most afraid of? Put your imagination and creative talents to work in order to come up with productive solutions to your problems. Pay attention to dream imagery (sleeping and daydreaming) and what your subconscious is trying to communicate."', '"Your love life is very structured right now. The Pope symbolizes traditional morals, values, etc., so you aren\'t willing to go too far out of the norm in order to snag or please a love interest. You can still follow convention and not be buttoned up quite so tight. You should be able to find a way to loosen up while still following the set of morals you choose to live by."'],
    "money" : ['"You may benefit from a fortunate transit through your house of money. You might find that working for a larger company or corporation is the best bet now because of the greater benefits you can get. The cosmos shows that you might need to think about how to take your skills to a more global market rather than limit yourself to what you have here."', '"This week is all about your house of debt and other people\'s money. You\'re in the midst of changing your money life for the better, but it might take some time before you can pull yourself out completely. Meanwhile, power players are encouraging you to communicate more, especially when it comes to your money. Don\'t let others decide for you."', '"You can get what you need - and probably also something you really want - from a current working situation, particularly compensation. You may need to consider target audiences or customer bases outside your country for greater success. Think about how to incorporate your spiritual life into your work. Your relationships will be helpful, supportive, and, most of all, productive."', '"Think about how to derive ongoing income from shared property and investments. This may be as simple as renting out an apartment or splitting dividends down the middle. But it also indicates the need to be careful about accruing more debt now, particularly if you aren\'t accustomed to budgeting. You\'re a powerhouse on the job, capable of doing it all and more."', '"An emphasis on self-employment gives you many reasons to form that new business that\'s been at the back of your mind for so long. Since your social segment is expanding, you can assemble a proper team to promote your ideas to a larger audience without feeling overwhelmed. Aspects bring new energy to your house of metaphysics, teaching, and learning. Cash flows when you share what you know in creative new ways."'],
    "happiness" : ['"The current planetary energy is likely to exacerbate your already sensitive nature. You may feel quite a lot of anxiety, and this could manifest in your digestion. Be sure to get plenty of exercise and drink plenty of water right now. Get in a yoga workout and do some deep breathing and lower abdominal stretching. While it may take some time, every single day matters to the big picture."', '"A great deal of emotional energy is at hand due to today\'s planetary positions, and no one will feel it more poignantly than you! Your natural inclination to take care of others is tapped by this placement and your emotional attachment to people close to you will grow more intense during these few days. To help some of the intense energy dissipate make it a point to get some exercise every day - preferably in the morning."', '"Your least favorite thing is to be blamed for causing some kind of disappointment, and you may find yourself caught in this type of bind this week. There\'s no way to really change your basic nature, but you can prevent certain situations from occurring. For starters, be honest with yourself about how busy you are and whether or not you can manage everything you need to get done for yourself before you make plans to help others."', '"If you can get some extra rest these days, it would be recommended. You\'ve been going a breakneck speed and your body is probably more tired than you realize. Your mind can go on completing tasks forever - it\'s rare that you change your plans to accommodate your body\'s needs! You can begin to address this tendency by \"scheduling\" regular yoga workouts into your week in order to learn to check in with how your body is really feeling."', '"The aspect of the day will quite possibly find you brooding about how to get a head start. For one thing, you cannot go wrong by paying attention to your body. If your mind is feeling foggy, don\'t let it stop you from getting out into the fresh air for an invigorating walk every day. If your heart is feeling blue, don\'t let that stop you from reaching out to people who care about you and asking for some extra TLC!"']
    }
    return random.choice(my_dict[flag])
   

# fortune_topic()


